version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - pwd
      - ls
      - cd customer-core
  build:
    commands:
      - echo Build started on `date`
      - pwd
      - ls
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - customer-core/target/customer-core-0.0.1-SNAPSHOT.jar
  discard-paths: yes